AWSTemplateFormatVersion: '2010-09-09'
Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
  S3Bucket:
    Type: AWS::S3::Bucket
  InstanceRole:
    Type: AWS::IAM::Role
  CloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm